//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.16 at 11:32:14 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.com.web.soap.crud/employ-information", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.web.crud.soap.stub;
